import { getSession } from 'next-auth/client';
import Head from 'next/head'
import Feed from '../components/Feed';
import Header from '../components/Header'
import Login from '../components/Login'
import Sidebar from '../components/Sidebar';
import Widgets from '../components/Widgets';
import { db } from '../firebase';

export default function Home({ session, stories, posts }) {

  if (!session ) return <Login />
  return (
    <div className="h-screen bg-gray-100 overflow-hidden">
      <Head>
        <title>Facebook Clone</title>
        <meta name="description" content="Generated by Lord_Qaisi" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      <main className="flex">
        {/* sidebar */}
        <Sidebar />

        {/* feed */}
        <Feed storiesFeed={stories} posts={posts}/>

        {/* widgets */}
        <Widgets contactsWidget={stories}/>
        
      </main>

     
    </div>
  );
}

export const getServerSideProps = async(context) => {
  const session = await getSession(context)

  const apiResponse = await fetch(`https://randomuser.me/api/?results=30`)
  const users = await apiResponse.json();

  const posts = await db.collection("posts").orderBy("timestamp", "desc").get();

  const docs = posts.docs.map(post => ({
    id: post.id,
    ...post.data(),
    timestamp: null
  }))

  return {
    props: {
      session,
      stories: users.results,
      posts: docs,
    }
  }
}
